version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: threadly
    volumes:
      - data:/var/lib/postgresql/data

  threadly:
    build: .
    volumes:
      - .:/threadly
    ports:
      - "3000:3000"
    env_file:
      - .threadly.env
    depends_on:
      - postgres

volumes:
  data: