version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: threadly
    volumes:
      - data-pg:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - data-redis:/data

  threadly:
    build: .
    volumes:
      - .:/threadly
    ports:
      - "3000:3000"
    env_file:
      - .threadly.env
    environment:
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis

volumes:
  data-pg:
  data-redis: